name: GitHub Actions Secret

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest

    steps:
      - name: Something about token
        run: |
          touch .env
          echo DISCORD_TOKEN=${{ secrets.TOKEN }} >> .env